name: Android Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'
    
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.3'

    - name: Generate local.properties
      run: |
        echo "flutter.compileSdkVersion=34" >> android/local.properties
        echo "flutter.minSdkVersion=24" >> android/local.properties
        echo "flutter.targetSdkVersion=34" >> android/local.properties
        echo "flutter.versionCode=3" >> android/local.properties
        echo "flutter.versionName=3.0" >> android/local.properties

    - name: Install dependencies
      run: flutter pub get

    - name: Build APK
      run: flutter build apk --debug

    - name: Upload APK to GitHub
      uses: actions/upload-artifact@v3
      with:
        name: android-release-apk
        path: build/app/outputs/flutter-apk/app-debug.apk
